/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Pagos;
import Clases.Servicio;
import Clases.tipoServicio;
import Principal.BaseDatos;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivanr
 */
public class framePagos extends javax.swing.JFrame {
    private int idCotizacion;
    DefaultTableModel dtm;
    BaseDatos bd= new BaseDatos();
    ArrayList<Pagos> listpagos = new ArrayList();
    /**
     * Creates new form framePagos
     */
    
    /**
    * Constructor de la clase FramePagos 
    * inicializa la clase
    * se utiliza al querer mostrar la interfaz
    * @param IDCOT identificador de la cotizacion
    */
    public framePagos(int IDCOT) {
        this.idCotizacion=IDCOT;
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dtm=(DefaultTableModel) tblPagos.getModel();
        initComponents();
        //buscar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jspTablePagos = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 229, 218));

        jPanel1.setBackground(new java.awt.Color(251, 229, 218));

        jspTablePagos.setBackground(new java.awt.Color(251, 229, 218));
        jspTablePagos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jspTablePagos.setForeground(new java.awt.Color(251, 229, 218));

        tblPagos.setBackground(new java.awt.Color(251, 229, 218));
        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO ", "CONCEPTO", "P.U."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPagos.setToolTipText("");
        tblPagos.setGridColor(new java.awt.Color(251, 229, 218));
        tblPagos.setSelectionBackground(new java.awt.Color(241, 172, 133));
        tblPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPagosMouseClicked(evt);
            }
        });
        tblPagos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblPagosKeyReleased(evt);
            }
        });
        jspTablePagos.setViewportView(tblPagos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspTablePagos, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(jspTablePagos, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPagosMouseClicked
        if(evt.getClickCount()==2){
  
        }
    }//GEN-LAST:event_tblPagosMouseClicked

    private void tblPagosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPagosKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
  
        }
    }//GEN-LAST:event_tblPagosKeyReleased
    
    /**
    * Funcion de busqueda en la base de datos
    * realiza una bosqueda en la tabla pagos de la cotizacion de dicha clase
    * se utuliza para obtener informaion sobre los pagos realizados
    */
     ////////////////////////buscar//////////////////////////////////
     private void buscar() {
        listpagos.clear();
        eliminarTb();
         
        ResultSet resultado=null;
        Connection connection=null;
        Statement statement=null;
        try {
            connection = bd.getConexion();
            statement = connection.createStatement();

            
            String selectSql = "SELECT * from PAGOS where ID_COTIZACION  ='"+idCotizacion+"'";
            resultado= statement.executeQuery(selectSql);
          
            while(resultado.next()){
            Pagos servicis = new Pagos(resultado.getBigDecimal("MONTO"),resultado.getBigDecimal("RESTANTE"),resultado.getDate("FECHA"));
            //System.out.println(servicis);
            listpagos.add(servicis);
            
            }
           
        } catch (Exception ex) {
            ex.printStackTrace();
            
        }finally{
            bd.cerrar(statement, resultado);
            llenarTabla();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePagos(13).setVisible(true);
            }
        });
    }
    
    /**
    * realizacion de llenado de tabla
    * Realiza llenado de la tabla de pagos con un arraylist pagos
    * se llama cada que se realice una demostracion de la tabla o se le haga cambio
    */
    
    public void llenarTabla(){
        eliminarTb();
         Object O[]=null;
         for (int i = 0; i < listpagos.size(); i++) {
            dtm.addRow(O);
            Pagos ser = (Pagos) listpagos.get(i);  
           dtm.setValueAt(ser.getFecha(), i, 0);
            dtm.setValueAt(ser.getMonto(), i, 1);
            dtm.setValueAt(ser.getRestante(), i, 2);
            }
     }
    
    
    /**
    * Reseteo de la tabla
    * realiza un reseteo de la tabla para poder actualizarla con campos nuevos
    * se utiliza al realizar una actualizacion den la tabla
    */
     public void eliminarTb(){
        int a = tblPagos.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        dtm.removeRow(dtm.getRowCount()-1);
        }
        //cargaTicket();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspTablePagos;
    private javax.swing.JTable tblPagos;
    // End of variables declaration//GEN-END:variables
}
